### ISSUE TITLE
Character Rapidly Accelerating Down falling through 1-way platform

### ISSUE THREAD

**Issue by Jkohuth** [reunono/CorgiEngineExtensions#32]
Character with CorgiController, CharacterJump, and CharacterHorizontalMovement accumulates speed in the negative Y direction when moving. If a character is walking against a wall on top of a 1-way platform for a duration of time and then to fall through the platform, that accumulated speed happens all at once thrusting the character downward.

_controller.SetVerticalForce(0) in the CharacterJump script seemed like the proper workaround for the time being

**Comment by reunono** [comment]
Seems unrelated to any extensions. Please use the support form to report bugs. Make sure you provide context info and repro steps in a fresh install, in any of the demos.
https://corgi-engine.moremountains.com/corgi-engine-contact
